### PR TITLE
Update ReadMe.md

### PR DESCRIPTION
**Pull request by williln**
Added Growstuff and OpenHatch; linked to Julie Pagano blog post of 4 good open source projects.

### CODE REVIEW

**Comment by pkafei** [comment]
Growstuff looks pretty cool! Thanks for sharing that resource :seedling:

**Comment by williln** [comment]
No problem! I'm glad you don't mind me just jumping in here. I just think your project is so cool and I wanna help. Also, I picked today (totally randomly) to start attacking Pyladies issues, so this is timely for me :)

**Comment by pkafei** [comment]
The more input the merrier. The next step of this project is to write a list of what makes contributing to OSS a positive experience for new comers. Can you tell me which strategies have worked for you?

**Comment by williln** [comment]
I am still super new to open source, but I can say: 
- Having someone directly ask me to contribute in some way 
- Having detailed documentation on how to get set up (WHY is setup so HARD) 
- Having someone who will go back and forth with me to help me (but only one person at a time-- when you get like 5 people jumping in with advice it feels overwhelming)

**Comment by pkafei** [comment]
Thank you. This is important- if we as a community are serious about bringing new people in, we need to directly address and remove some of the technical and emotional barriers that newbies face when jumping into a new OSS project.

**Pull request merged**
